language: php

php:
  - 5.6
  - 7.0
  - 7.1

sudo: false

env:
  global:
    - PHPUNIT=1

matrix:
  fast_finish: true

  allow_failures:

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction

  - sh -c "if [ '$PHPCS' = '1' ]; then composer require cakephp/cakephp-codesniffer:dev-master; fi"

  - phpenv rehash
  - set +H
  - cp phpunit.xml.dist phpunit.xml

script:
  - sh -c "if [ '$PHPUNIT' = '1' ]; then vendor/bin/phpunit; fi"

  - sh -c "if [ '$PHPCS' = '1' ]; then vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests; fi"

notifications:
  email: false
